version: '3'

volumes:
  mongo:

services:
  api:
    build:
      context: .
      dockerfile: DockerFile
    command: pm2-dev app.js --node-args="--max-old-space-size=4096"
    restart: always
    env_file:
      - .env
    volumes:
    - .:/app
    - /app/node_modules
    ports:
      - 3001:3002
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

